In [14]:
from __future__ import print_function
import torch

# torch tensor plays the center role as array in numpy
x = torch.Tensor(5,3) #uninitialized
print(x)


-1.0915e+20  4.5883e-41 -2.2781e+26
 3.0627e-41  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
-5.4570e-30  4.5883e-41 -5.4570e-30
[torch.FloatTensor of size 5x3]



In [15]:
x = torch.rand(5,3) #randomly initialized
print(x)


 0.8719  0.0188  0.0863
 0.6489  0.2915  0.7572
 0.9932  0.7447  0.5408
 0.0100  0.3956  0.7545
 0.1547  0.3707  0.6055
[torch.FloatTensor of size 5x3]



In [16]:
print(x.size())

torch.Size([5, 3])


In [17]:
# there are multiple syntaxes for operations
y = torch.rand(5,3)
print(x+y)


 1.6233  0.6078  0.2727
 1.3536  1.1087  1.3706
 1.2144  1.6981  1.3525
 0.6568  0.8154  1.7141
 0.5945  0.8965  0.7120
[torch.FloatTensor of size 5x3]



In [18]:
print(torch.add(x,y))


 1.6233  0.6078  0.2727
 1.3536  1.1087  1.3706
 1.2144  1.6981  1.3525
 0.6568  0.8154  1.7141
 0.5945  0.8965  0.7120
[torch.FloatTensor of size 5x3]



In [19]:
# or giving a output tensor 
result = torch.Tensor(5,3)
torch.add(x,y,out = result)
print(result)


 1.6233  0.6078  0.2727
 1.3536  1.1087  1.3706
 1.2144  1.6981  1.3525
 0.6568  0.8154  1.7141
 0.5945  0.8965  0.7120
[torch.FloatTensor of size 5x3]



In [20]:
# or add in-place
y.add_(x)
print(y)
# any operation that mutates a tensor in-place is post fixed
# with an _ for example:x.copy_(y),x.t_(), will change x
x.t_()
print(x)


 1.6233  0.6078  0.2727
 1.3536  1.1087  1.3706
 1.2144  1.6981  1.3525
 0.6568  0.8154  1.7141
 0.5945  0.8965  0.7120
[torch.FloatTensor of size 5x3]


 0.8719  0.6489  0.9932  0.0100  0.1547
 0.0188  0.2915  0.7447  0.3956  0.3707
 0.0863  0.7572  0.5408  0.7545  0.6055
[torch.FloatTensor of size 3x5]



In [21]:
# we can use standard nmpy-like indexing for tensor 
print(x[:,1])
# there exist more than 100 tensor operations 


 0.6489
 0.2915
 0.7572
[torch.FloatTensor of size 3]



In [22]:
# the torch tensor and numpy array will share same mermory 
# location, changing one will change another 
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [23]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [24]:
a.add_(1)
print(a)
print(b) #array b changes too


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) #convert array to tensor
np.add(a,1,out=a)
print(a)
print(b) #b changes as a changes 

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [26]:
#CUDA tensors: tensors can be moved onto GPU uing .cuda
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x+y