In [1]:
print("Everybody read that book".split())

['Everybody', 'read', 'that', 'book']


In [2]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1) # random num generator 

In [13]:
lstm = nn.LSTM(3, 3)  # Input dim is 3, output dim is 3

# make a random sequence of length 5, dim_feat 3
inputs = [autograd.Variable(torch.randn((1, 3)))
          for _ in range(5)] 

# initialize the hidden state. 
hidden = (autograd.Variable(torch.randn(1, 1, 3)),
          autograd.Variable(torch.randn((1, 1, 3))))

for i in inputs:
    # Step through the sequence one element at a time.
    # lstm input must be 3d tensor, so generate a fake one 1x1x3 with view
    out, hidden = lstm(i.view(1, 1, -1), hidden)
    print(i.view(1, 1, -1))
    print(out)
    print(hidden)
    print('next step')
    

Variable containing:
(0 ,.,.) = 
 -2.0339  1.0273  0.1824
[torch.FloatTensor of size 1x1x3]

Variable containing:
-0.1315
[torch.FloatTensor of size 1]

(Variable containing:
(0 ,.,.) = 
 -0.1315  0.0005 -0.0497
[torch.FloatTensor of size 1x1x3]
, Variable containing:
(0 ,.,.) = 
 -0.3820  0.0008 -0.3134
[torch.FloatTensor of size 1x1x3]
)
next step
Variable containing:
(0 ,.,.) = 
 -0.8898  1.6604  0.6113
[torch.FloatTensor of size 1x1x3]

Variable containing:
1.00000e-03 *
  1.7922
[torch.FloatTensor of size 1]

(Variable containing:
(0 ,.,.) = 
  0.0018 -0.1380 -0.0150
[torch.FloatTensor of size 1x1x3]
, Variable containing:
(0 ,.,.) = 
  0.0033 -0.1918 -0.0728
[torch.FloatTensor of size 1x1x3]
)
next step
Variable containing:
(0 ,.,.) = 
  0.8490 -1.4300  0.3975
[torch.FloatTensor of size 1x1x3]

Variable containing:
-0.1476
[torch.FloatTensor of size 1]

(Variable containing:
(0 ,.,.) = 
 -0.1476  0.0261 -0.1521
[torch.FloatTensor of size 1x1x3]
, Variable containing:
(0 ,.,.) = 


In [20]:
import numpy as np
a = np.arange(15).reshape(3, 5)
b = np.array([[6, 7, 8],a 
              [3, 4, 5]])
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [22]:
c.dtype

dtype('complex128')

In [31]:
d = np.random.random((2,3))
print(d)
d.sum(axis=1)

[[ 0.19722887  0.38423995  0.19222589]
 [ 0.02360551  0.38484693  0.25716588]]


array([ 0.77369471,  0.66561832])

In [36]:
a = np.array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])
a[0:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a[0:6:2] # for(index = 0; index <6; index += 2)

array([-1000, -1000, -1000])

In [58]:
a = np.arange(15)
a[[0,1,3]] = [0, 0, 0] 
a 

array([ 0,  0,  2,  0,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])